RandomForest:
 n_estimators: 200
 max_depth: 10
 random_state: 42

DecisionTree:
  max_depth: 5
  criterion: "squared_error"
  random_state: 42

GradientBoosting:
  n_estimators: 200
  learning_rate: 0.1
  max_depth: 3
  random_state: 42

LinearRegression: {}

XGBRegressor:
  n_estimators: 300
  learning_rate: 0.05
  max_depth: 6
  random_state: 42

CatBoost:
  iterations: 300
  depth: 6
  learning_rate: 0.1
  verbose: False

AdaBoost:
  n_estimators: 150
  learning_rate: 0.05
  random_state: 42